-- v18.36 — Módulo de Soporte: el cliente reporta problemas desde la app
-- El ticket vive acá (fuente de la verdad). WhatsApp es solo el aviso: el
-- reclamo queda registrado aunque nadie llegue a mandar el mensaje.
-- El adjunto va al bucket soporte-adjuntos; en la tabla se guarda el PATH,
-- no la URL, para poder regenerar un link firmado cuando se quiera mirar.

-- 1) Tabla principal
CREATE TABLE IF NOT EXISTS soportes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero INT GENERATED BY DEFAULT AS IDENTITY,
  modulo TEXT NOT NULL DEFAULT '',
  descripcion TEXT NOT NULL DEFAULT '',
  -- true = no puede seguir trabajando. Es el campo que ordena la cola.
  bloqueante BOOLEAN NOT NULL DEFAULT false,
  adjunto_path TEXT,
  estado TEXT NOT NULL DEFAULT 'abierto'
    CHECK (estado IN ('abierto', 'en_revision', 'resuelto')),
  respuesta TEXT DEFAULT '',
  -- Contexto capturado solo por la app, para no depender de que el usuario
  -- sepa explicar dónde estaba cuando falló.
  reportado_por TEXT,
  rol TEXT,
  app_version TEXT,
  plataforma TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  resuelto_en TIMESTAMPTZ,
  resuelto_por TEXT
);

CREATE INDEX IF NOT EXISTS idx_soportes_estado ON soportes (estado);
CREATE INDEX IF NOT EXISTS idx_soportes_creado
  ON soportes (creado_en DESC);

ALTER TABLE soportes DISABLE ROW LEVEL SECURITY;

-- 2) Bucket de adjuntos (privado: las capturas muestran datos de clientes).
-- Límite 10 MB. Se aceptan los formatos que manda un iPhone, incluido HEIC.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'soporte-adjuntos',
  'soporte-adjuntos',
  false,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO NOTHING;

-- 3) Policies de Storage.
-- La app se conecta con la publishable key (rol anon), así que el acceso al
-- bucket se habilita para anon y acotado a este bucket. SELECT es necesario
-- para poder firmar URLs; sin él, createSignedUrl falla.
DROP POLICY IF EXISTS "soporte_adjuntos_insert" ON storage.objects;
CREATE POLICY "soporte_adjuntos_insert" ON storage.objects
  FOR INSERT TO anon
  WITH CHECK (bucket_id = 'soporte-adjuntos');

DROP POLICY IF EXISTS "soporte_adjuntos_select" ON storage.objects;
CREATE POLICY "soporte_adjuntos_select" ON storage.objects
  FOR SELECT TO anon
  USING (bucket_id = 'soporte-adjuntos');
